file:
  image:
    path: d:/myOII/img/
    originPath: /image/**
    toPath: file:/d:/myOII/img/
  default:
    path: d:/myOII
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myinfo?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
